services:
  server:
    image: harshpatil20/uber-server:latest  # Use pre-built backend image
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env  # Load environment variables
    environment:
      - DB_CONNECT=mongodb://mongo:27017/uberdb
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    image: harshpatil20/uber-client:latest  # Use pre-built frontend image
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://server:3000  # Use service name instead of localhost
    depends_on:
      - server
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:  # Custom network for inter-service communication

volumes:
  mongo-data:  # Named volume for persistent MongoDB data
